; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:custom_esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_mode = qio
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = default.csv
lib_deps = 
	pilotak/MovingAverage
	khoih-prog/WebSockets_Generic
	pangodream/ESP2SOTA@^1.0.2
	stevemarple/SoftWire@^2.0.10
	vshymanskyy/TinyGSM@^0.12.0
	knolleary/PubSubClient@^2.8
lib_ignore = 
	WiFiEspAT
	UIPEthernet
	EthernetENC
	WiFi101
	WiFi101_Generic
	WiFiNINA_Generic
	DueFlashStorage
	SinricPro_Generic
build_flags = 
	-D CORE_DEBUG_LEVEL=3
	-D CONFIG_FREERTOS_HZ=1000
	-Wno-unused-variable
	-I include
build_src_filter = 
	+<*>
	-<EC200U_LTE.cpp>
	-<EC200U_Integration_Example.cpp>
